version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/onedoctor
      - OPENAI_API_KEY=your_openai_api_key
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onedoctor
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
